apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate

metadata:
  name: success-rate
  namespace: gitops-demo

spec:
  metrics:
  - name: success-rate
    interval: 30s
    count: 1
    successCondition: result[0] > 0
    failureLimit: 1

    provider:
      prometheus:
        address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

        query: |
          (
            sum(rate(http_request_total[1m]))
          )