apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: zero-downtime-gitops
  namespace: gitops-demo

spec:
  replicas: 3

  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause:
          duration: 30s

      - setWeight: 50
      - pause:
          duration: 30s

      - setWeight: 100

  selector:
    matchLabels:
      app: zero-downtime-gitops

  template:
    metadata:
      labels:
        app: zero-downtime-gitops

    spec:
      containers:
      - name: flask-app

        image: ghcr.io/muhammad-ahmadd-shafiq/zero-downtime-gitops:38c1b06f56f143d8cc006b1b6fa53ccd3459e7ab

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"