---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: gitops-demo
spec:
  encryptedData:
    API_KEY: AgB0t5RfuOpx5PMoHK5PmBze1PCmKO6R8+K6CYd+KrTanaZNMuOF7FZfB8JtkvywZ8fPeQR5x89yfWytvBYJaMYplKVu1AlRs7o4C2grcyMj6PxTisC8Z2u6hJKSml9+ph8j/tPqKmiJeWK6okI+CfQAGGSOoJKtdKRz4pjSCTwzt4cPt14pH5ywq+VHW/QSf0fNlPVeDd3W7JXzWSBBCLIjW2bnS6nQ824pvHnuJjPLBzeP5Utu+MWs1sRpJr5UwWpkhm0SDXEj7mUEDx+CmhtIiCQhtU2d6afM7bExdlrTM6NLazDsGJFHHVd+QuDw+Tulbgh/KZRtJonEergy4LCngNQ9w3qM5m9hMXTPDhs4JoRwKYIrtSX5X2mCVkrOpwYiFRCLoLxoLVjPEswrTcM2u6m7J+G0MyTEP/ZIRxbUqIsASQkpvRyf8Pck4+Ptone7DF83NSR4qU7SwlFC98KnLdqThjVBrYIrsWsasjezWg+fTM9wkDSrA4mfdHT1SUO5waXANoT1lGf7amHiPmmnHwTlnYXxD2UtzBaCZHgEV7XmuZjuJzbKhpgdEG/fyaYayRb/N8a6o084t/YZLk0/pQms4V2vEAaWMx5RDmmzDq7XzlQ8cLMF9vZuWGQblAE/oDoy6beN3UNYxsV7QX0lOl0YbECce+uNBtYrJpZd4uo0P+NwjgzvX6eJ4OKv3AsAk1tg68NWuwNoFI/mGs/z
  template:
    metadata:
      name: app-secret
      namespace: gitops-demo
