apiVersion: v1
kind: Service

metadata:
  name: zero-downtime-service
  namespace: gitops-demo

spec:
  selector:
    app: zero-downtime-gitops

  ports:
  - port: 80
    targetPort: 5000

  type: ClusterIP