apiVersion: v1
kind: Service

metadata:
  name: zero-downtime-service
  namespace: gitops-demo

  labels:
    app: zero-downtime-gitops

spec:
  selector:
    app: zero-downtime-gitops

  ports:
  - name: http
    port: 80
    targetPort: 5000