apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: zero-downtime-gitops
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/muhammad-ahmadd-shafiq/zero-downtime-gitops.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
